# Default settings
#
# Syntax can be learned from Dynaconf examples 
# https://github.com/rochacbruno/learndynaconf/tree/main/configs

[schedule]
api = "https://scheduler-uobd.onrender.com/api/v1/schedule/"
length_minutes = 1
policy = "dummy"
